export const getNutrientName: Record<string, string> = {
  weight: 'Weight',
  vitaminA: 'Vitamin A',
  alcohol: 'Alcohol',
  calcium: 'Calcium',
  calories: 'Calories',
  carbs: 'Carbohydrates',
  cholesterol: 'Cholesterol',
  fat: 'Fat',
  fibers: 'Dietary Fiber',
  iodine: 'Iodine',
  iron: 'Iron',
  magnesium: 'Magnesium',
  monounsaturatedFat: 'Monounsaturated Fat',
  phosphorus: 'Phosphorus',
  polyunsaturatedFat: 'Polyunsaturated Fat',
  potassium: 'Potassium',
  protein: 'Protein',
  satFat: 'Saturated Fat',
  sodium: 'Sodium',
  sugarAlcohol: 'Sugar Alcohol',
  sugars: 'Sugars',
  sugarsAdded: 'Added Sugars',
  transFat: 'Trans Fat',
  vitaminB12: 'Vitamin B12',
  vitaminB12Added: 'Added Vitamin B12',
  vitaminB6: 'Vitamin B6',
  vitaminC: 'Vitamin C',
  vitaminD: 'Vitamin D',
  vitaminE: 'Vitamin E',
  vitaminEAdded: 'Vitamin E Added',
}
