require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

use_frameworks!

platform :ios, '11.0'

target 'ReactNativePassioSDK' do

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  # Pods for ReactNativePassioSDK
end
